user  nginx;
worker_processes  auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen       80;
        server_name  localhost;

        access_log  /var/log/nginx/default_access.log;
        error_log   /var/log/nginx/default_error.log;

        location /auth/ {
            proxy_pass http://traffic-auth:8080;
        }

        location /api/ {
            proxy_pass http://traffic-api:8081;
        }
    }
}
