spring:
  application:
    name: traffic-auth
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/traffic?currentSchema=auth
    username: auth
    password: auth123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        '[format_sql]': true
      ddl-auto: none
    generate-ddl: true

springdata:
  redis:
    port: 6379
    host: 127.0.0.1



